# Generated by Django 5.1.2 on 2026-03-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Entidad certificadora',
                'verbose_name_plural': 'Entidades certificadoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4, unique=True)),
            ],
            options={
                'verbose_name': 'Nota de certificación',
                'verbose_name_plural': 'Notas de certificación',
                'ordering': ['-grade'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'TCG',
                'verbose_name_plural': 'TCGs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de descuento (0 = sin descuento).')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Dejar vacío si es un producto único (slab, single).', null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('image_url_2', models.URLField(blank=True, max_length=600)),
                ('image_url_3', models.URLField(blank=True, max_length=600)),
                ('pricecharting_url', models.URLField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_entity', models.ForeignKey(blank=True, help_text='Solo para Slabs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.certificationentity')),
                ('certification_grade', models.ForeignKey(blank=True, help_text='Solo para Slabs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.certificationgrade')),
                ('condition', models.ForeignKey(blank=True, help_text='Solo para Singles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.cardcondition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
                ('tcg', models.ForeignKey(blank=True, help_text='Obligatorio para Singles, Slabs y Sellados. Opcional para Accesorios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.tcg')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
