# Generated by Django 5.1.2 on 2026-03-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
            },
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
                'ordering': ['tcg', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de producto',
            },
        ),
        migrations.CreateModel(
            name='TCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'TCG',
                'verbose_name_plural': 'TCGs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de descuento directo (0 = sin descuento).')),
                ('is_single', models.BooleanField(default=True, help_text='True = carta suelta (1 unidad). False = producto con cantidad.')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Solo para productos no-single. Dejar vacío si es single.', null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('image_url_2', models.URLField(blank=True, max_length=600)),
                ('image_url_3', models.URLField(blank=True, max_length=600)),
                ('pricecharting_url', models.URLField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.cardcondition')),
                ('expansion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.expansion')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.producttype')),
                ('tcg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.tcg')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expansion',
            name='tcg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansions', to='products.tcg'),
        ),
    ]
