# Generated by Django 5.1.2 on 2026-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares. El sistema convierte a ARS automáticamente.', max_digits=10),
            preserve_default=False,
        ),
    ]
