# Generated by Django 5.1.2 on 2026-04-04 02:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcondition',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='cardcondition',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='certificationentity',
            name='abbreviation',
            field=models.CharField(max_length=20, unique=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='certificationentity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='certificationgrade',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=4, unique=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certification_entity',
            field=models.ForeignKey(blank=True, help_text='Solo para Slabs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.certificationentity', verbose_name='Certificadora'),
        ),
        migrations.AlterField(
            model_name='product',
            name='certification_grade',
            field=models.ForeignKey(blank=True, help_text='Solo para Slabs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.certificationgrade', verbose_name='Nota certificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, help_text='Solo para Singles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.cardcondition', verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje de descuento (0 = sin descuento).', verbose_name='% Descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, max_length=600, verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, max_length=600, verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='En stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Precio en dólares. El sistema convierte a ARS automáticamente.', max_digits=10, verbose_name='Precio USD'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricecharting_url',
            field=models.URLField(blank=True, max_length=600, verbose_name='URL PriceCharting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Calificación promedio del producto (0.0 – 5.0).', max_digits=3, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de calificaciones recibidas.', verbose_name='Cant. calificaciones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Dejar vacío si es un producto único (slab, single). Para Singles y Slabs, el sistema fuerza automáticamente stock = 1 si el producto está en stock.', null=True, verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tcg',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para Singles, Slabs y Sellados. Opcional para Accesorios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.tcg', verbose_name='TCG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tcg',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
