# Generated by Django 5.2 on 2026-08-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0010_productimage_productimagewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_card',
            field=models.ForeignKey(blank=True, help_text='Buscá la carta para autocompletar nombre, set, número, rareza e imagen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.catalogcard', verbose_name='Carta del catálogo'),
        ),
    ]
