# Generated by Django 5.2 on 2026-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_catalog_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Unidades apartadas por órdenes de pago manual (efectivo, transferencia, crypto) que todavía no se cobraron. No se venden, pero siguen siendo tuyas hasta que marques la orden como pagada.', verbose_name='Reservado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Unidades disponibles de esta publicación. Si tenés la misma carta repetida en el mismo estado, subí la cantidad acá en vez de cargarla de nuevo. Vacío en Singles y Slabs se toma como 1.', null=True, verbose_name='Cantidad en stock'),
        ),
    ]
