# Generated by Django 5.2 on 2026-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Unidades apartadas por órdenes por transferencia que todavía no se confirmaron. No se venden, pero siguen siendo tuyas hasta que marques la orden como pagada.', verbose_name='Reservado'),
        ),
    ]
