# Generated by Django 5.2 on 2026-10-08 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogcard_search_trigram_index'),
        ('products', '0013_alter_product_reserved_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Carga masiva',
                'verbose_name_plural': 'Cargas masivas',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_card', 'in_stock'], name='product_card_stock_idx'),
        ),
        migrations.AddField(
            model_name='bulkloadreceipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
