# Generated by Django 5.2 on 2026-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bulkloadreceipt_product_product_card_stock_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='altered',
            field=models.BooleanField(default=False, verbose_name='Alterada'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Acabado'),
        ),
        migrations.AddField(
            model_name='product',
            name='freshly_opened',
            field=models.BooleanField(default=False, help_text='Sacada de un sobre recién abierto.', verbose_name='Recién abierta'),
        ),
        migrations.AddField(
            model_name='product',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Firmada'),
        ),
        migrations.AddField(
            model_name='product',
            name='stamped',
            field=models.BooleanField(default=False, verbose_name='Estampada'),
        ),
    ]
