# Generated by Django 5.2 on 2026-10-08 14:17

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def language_from_catalog(apps, schema_editor):
    """Los productos que ya salieron del catálogo toman el idioma de su set."""
    Product = apps.get_model("products", "Product")
    CatalogCard = apps.get_model("catalog", "CatalogCard")
    Product.objects.filter(catalog_card__isnull=False, language="").update(
        language=Subquery(
            CatalogCard.objects.filter(pk=OuterRef("catalog_card_id")).values("card_set__language")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_cardset_printings_synced_at_catalogcard_printings"),
        ('products', '0015_product_altered_product_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'Inglés'), ('es', 'Español'), ('pt', 'Portugués'), ('ja', 'Japonés'), ('zh', 'Chino')], db_index=True, default='', max_length=2, verbose_name='Idioma'),
        ),
        migrations.RunPython(language_from_catalog, migrations.RunPython.noop),
    ]
