# Generated by Django 5.2 on 2026-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Detalle'),
        ),
    ]
