# Generated by Django 5.1.2 on 2026-04-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0008_alter_cardcondition_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activado el'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto descuento'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=20, verbose_name='Tipo de descuento'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (segundos)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expiration_type',
            field=models.CharField(choices=[('none', 'Sin expiración'), ('date', 'Fecha fija'), ('duration', 'Duración tras activación')], default='none', max_length=20, verbose_name='Tipo de expiración'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True, verbose_name='Máx. usos'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='used',
            field=models.BooleanField(default=False, help_text='Marcar para invalidar manualmente', verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Usos'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido desde'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_payments', to='orders.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='ID pago'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='preference_id',
            field=models.CharField(max_length=150, unique=True, verbose_name='ID preferencia'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Respuesta completa de MP', null=True, verbose_name='Respuesta cruda'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=20, verbose_name='Tipo descuento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_branch',
            field=models.CharField(blank=True, help_text='Sucursal de correo si aplica', max_length=255, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('home', 'Envío a domicilio'), ('pickup', 'Retiro en local')], default='home', max_length=20, verbose_name='Tipo de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Nombre producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario'),
        ),
    ]
