# Generated by Django 5.2 on 2026-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_discountcode_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, help_text='Generado automáticamente. Usado como external_reference en MercadoPago.', max_length=8, unique=True, verbose_name='Código de orden'),
        ),
    ]
