# Generated by Django 5.2 on 2026-05-12 18:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_shipping_config(apps, schema_editor):
    ShippingConfig = apps.get_model('orders', 'ShippingConfig')
    keys = [
        'branch_normal_ba',
        'branch_express_ba',
        'branch_normal_province',
        'branch_express_province',
        'home_ba',
        'home_province',
    ]
    for key in keys:
        ShippingConfig.objects.get_or_create(key=key, defaults={'price': Decimal('0')})


def backfill_order_shipping_fields(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Shipment = apps.get_model('orders', 'Shipment')

    ba_names = {
        'buenos aires',
        'caba',
        'ciudad autonoma de buenos aires',
        'ciudad autónoma de buenos aires',
        'capital federal',
    }

    for order in Order.objects.all().iterator():
        shipping_type = (order.shipping_type or '').strip()
        province = (order.shipping_province or '').strip().lower()
        shipping_cost = order.shipping_cost or Decimal('0')

        shipping_zone = 'ba' if province in ba_names else 'province'
        if shipping_type == 'pickup':
            shipping_method = 'branch_normal'
        else:
            shipping_method = 'home'

        has_shipping = bool(
            shipping_type in {'home', 'pickup'}
            or order.shipping_address
            or order.shipping_branch
            or shipping_cost > 0
        )

        order.shipping_method = shipping_method
        order.shipping_zone = shipping_zone
        order.shipping_price = shipping_cost
        order.has_shipping = has_shipping
        order.shipping_status = 'pending'
        order.save(
            update_fields=[
                'shipping_method',
                'shipping_zone',
                'shipping_price',
                'has_shipping',
                'shipping_status',
                'updated_at',
            ]
        )

        if has_shipping:
            Shipment.objects.get_or_create(
                order_id=order.id,
                defaults={'status': 'pending'}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_mercadopagopayment_expiration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('branch_normal_ba', 'Sucursal Normal BA'), ('branch_express_ba', 'Sucursal Express BA'), ('branch_normal_province', 'Sucursal Normal Provincia'), ('branch_express_province', 'Sucursal Express Provincia'), ('home_ba', 'Domicilio BA'), ('home_province', 'Domicilio Provincia')], max_length=64, unique=True, verbose_name='Clave')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de envío',
                'verbose_name_plural': 'Configuraciones de envíos',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='has_shipping',
            field=models.BooleanField(default=False, verbose_name='Tiene envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('branch_normal', 'Sucursal Normal'), ('branch_express', 'Sucursal Express'), ('home', 'Domicilio')], default='', max_length=20, verbose_name='Método de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Despachado')], default='pending', max_length=20, verbose_name='Estado envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(blank=True, choices=[('ba', 'Buenos Aires'), ('province', 'Provincia')], default='', max_length=20, verbose_name='Zona envío'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=120, verbose_name='Código de seguimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Despachado')], default='pending', max_length=20, verbose_name='Estado')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de despacho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_shipping_config, migrations.RunPython.noop),
        migrations.RunPython(backfill_order_shipping_fields, migrations.RunPython.noop),
    ]
