# Generated by Django 5.2 on 2026-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_shippingconfig_shippingorder_order_has_shipping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(
                choices=[
                    ("correo_argentino", "Correo Argentino"),
                    ("andreani", "Andreani"),
                ],
                default="correo_argentino",
                max_length=30,
                verbose_name="Empresa de correo",
            ),
        ),
    ]
