# Generated by Django 5.2 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_shipment_carrier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagada"),
                    ("expired", "Vencida"),
                    ("refunded", "Devolución"),
                    ("cancelled", "Cancelada"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
