# Generated by Django 5.2 on 2026-05-20

from django.db import migrations


def backfill_shipping_type_from_method(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    Order.objects.exclude(shipping_method="pickup_store").update(
        shipping_type="home",
        has_shipping=True,
    )

    Order.objects.filter(shipping_method="pickup_store").update(
        shipping_type="pickup",
        has_shipping=False,
        shipping_status="pending",
    )


def reverse_backfill_shipping_type_from_method(apps, schema_editor):
    # Reverse no-op: previous incorrect values cannot be reconstructed reliably.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_status_expired"),
    ]

    operations = [
        migrations.RunPython(
            backfill_shipping_type_from_method,
            reverse_backfill_shipping_type_from_method,
        ),
    ]
