# Generated by Django 5.2 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_backfill_shipping_type_from_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_ready_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en la que se envio el aviso de retiro preparado al cliente.",
                null=True,
                verbose_name="Aviso de retiro preparado",
            ),
        ),
    ]
