# Generated by Django 5.2 on 2026-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_pickup_ready_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_status',
            field=models.CharField(choices=[('none', 'Sin efecto'), ('reserved', 'Reservado'), ('consumed', 'Descontado'), ('released', 'Devuelto al stock')], default='none', max_length=20, verbose_name='Estado del stock'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('branch_normal', 'Sucursal Normal'), ('branch_express', 'Sucursal Express'), ('home', 'Domicilio'), ('pickup_store', 'PickUp en tienda')], default='', max_length=20, verbose_name='Método de envío'),
        ),
    ]
