# Generated by Django 5.2 on 2026-09-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_card_surcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
            ],
            options={
                'verbose_name': 'Log de orden',
                'verbose_name_plural': 'Logs de órdenes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
