# Generated by Django 5.2 on 2026-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_content_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Comprobante (tipo)'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_key',
            field=models.CharField(blank=True, default='', help_text='Ruta del archivo en el bucket privado de comprobantes.', max_length=255, verbose_name='Comprobante (clave R2)'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comprobante (nombre)'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Comprobante subido el'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('transfer', 'Transferencia')], default='mercadopago', max_length=20, verbose_name='Método de pago'),
        ),
    ]
