# Generated by Django 5.2 on 2026-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_backfill_transfer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto desc. manual (histórico)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% desc. manual aplicado (histórico)'),
        ),
    ]
