# Generated by Django 5.2 on 2026-10-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(help_text='`sub` del JWT. Es lo único que une esta fila con Supabase.', max_length=64, unique=True, verbose_name='ID en Supabase')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verificado')),
                ('provider', models.CharField(blank=True, help_text='google, email…', max_length=30, verbose_name='Entró con')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Último ingreso')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
