# Generated by Django 5.2 on 2026-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Nombre de la sucursal de correo (opcional).', max_length=150, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='kind',
            field=models.CharField(choices=[('home', 'Domicilio'), ('branch', 'Sucursal de correo')], default='home', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Predeterminada dentro de su tipo.', verbose_name='Predeterminada'),
        ),
    ]
