# Generated by Django 5.2 on 2026-08-25 14:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para ocultar la calculadora y frenar pedidos nuevos.', verbose_name='Sección activa')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Se aplica sobre el precio de la publicación.', max_digits=5, verbose_name='% comisión')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('7'), help_text='Sales tax del estado del courier. Se aplica sobre el precio de la publicación.', max_digits=5, verbose_name='% tax')),
                ('arg_shipping_raw', models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Costo de traer una carta suelta desde Miami.', max_digits=10, verbose_name='Envío a Argentina — Raw (USD)')),
                ('arg_shipping_graded', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Costo de traer una carta calificada (slab) desde Miami.', max_digits=10, verbose_name='Envío a Argentina — Graded (USD)')),
                ('us_zip', models.CharField(default='33122', help_text='eBay cotiza el envío contra este código postal. Sin esto no devuelve costo de envío.', max_length=10, verbose_name='ZIP del courier en EE.UU.')),
                ('us_country', models.CharField(default='US', max_length=2, verbose_name='País del courier')),
                ('marketplace_id', models.CharField(default='EBAY_US', help_text='Header X-EBAY-C-MARKETPLACE-ID. Normalmente EBAY_US.', max_length=30, verbose_name='Marketplace')),
                ('default_ebay_shipping', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Se usa cuando la publicación no informa costo de envío.', max_digits=10, verbose_name='Envío eBay por defecto (USD)')),
                ('quote_ttl_minutes', models.PositiveIntegerField(default=60, help_text='Pasado este tiempo la cotización guardada en el carrito se vuelve a pedir.', verbose_name='Validez de la cotización (minutos)')),
                ('max_items_per_order', models.PositiveIntegerField(default=20, verbose_name='Máx. ítems por pedido')),
                ('max_quantity_per_item', models.PositiveIntegerField(default=10, verbose_name='Máx. unidades por publicación')),
                ('whatsapp_number', models.CharField(default='541150588131', help_text='Solo números, con código de país. Se usa en los links wa.me de los emails.', max_length=20, verbose_name='WhatsApp')),
                ('intro_text', models.TextField(blank=True, default='Ingresá el enlace de eBay y conocé el costo final de importación, con todos los gastos incluidos.', verbose_name='Texto de la sección')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de importación eBay',
                'verbose_name_plural': 'Configuración de importación eBay',
            },
        ),
        migrations.CreateModel(
            name='EbayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, db_index=True, help_text='Generado automáticamente. Es lo que el cliente usa para seguir el pedido.', max_length=8, unique=True, verbose_name='Código de pedido')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Retiro en tienda'), ('home', 'Envío a domicilio'), ('branch', 'Envío a sucursal')], default='pickup', max_length=20, verbose_name='Tipo de entrega')),
                ('shipping_address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('shipping_city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('shipping_province', models.CharField(blank=True, max_length=120, verbose_name='Provincia')),
                ('shipping_zip', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('shipping_branch', models.CharField(blank=True, max_length=255, verbose_name='Sucursal')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Comentarios del cliente')),
                ('status', models.CharField(choices=[('pending_review', 'Pendiente de aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('payment_received', 'Pago recibido'), ('in_argentina', 'En Argentina'), ('delivered', 'Entregada'), ('blocked', 'Frenada')], db_index=True, default='pending_review', max_length=30, verbose_name='Estado')),
                ('rejection_message', models.TextField(blank=True, help_text='Se incluye en el email que recibe el cliente.', verbose_name='Motivo del rechazo')),
                ('block_reason', models.TextField(blank=True, help_text='Por qué no se pudo confirmar el pedido (publicación agotada o caída).', verbose_name='Motivo del freno')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% comisión aplicado')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% tax aplicado')),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio publicaciones')),
                ('commission_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax')),
                ('ebay_shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Envío eBay')),
                ('arg_shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Envío a Argentina')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('has_price_changes', models.BooleanField(default=False, help_text='Algún ítem cambió de precio entre la cotización y la confirmación.', verbose_name='Hubo cambios de precio')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobada el')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rechazada el')),
                ('payment_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago recibido el')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Llegó a Argentina el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pedido eBay',
                'verbose_name_plural': 'Pedidos eBay',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbayOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(db_index=True, max_length=40, verbose_name='Item ID')),
                ('ebay_url', models.URLField(max_length=1000, verbose_name='Link de la publicación')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Imagen')),
                ('item_type', models.CharField(choices=[('raw', 'Raw'), ('graded', 'Graded')], default='raw', max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio publicación')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax')),
                ('ebay_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Envío eBay')),
                ('arg_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Envío a Argentina')),
                ('price_changed', models.BooleanField(default=False, verbose_name='Cambió de precio')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que vio el cliente al agregarlo, si difiere del precio final.', max_digits=12, null=True, verbose_name='Precio cotizado originalmente')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ebay.ebayorder', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
                'ordering': ['id'],
            },
        ),
    ]
