# Generated by Django 5.2 on 2026-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_remove_ebayconfig_arg_shipping_graded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayconfig',
            name='marketplace_id',
            field=models.CharField(default='EBAY_US', help_text='Sitio de eBay contra el que se cotiza.', max_length=30, verbose_name='Marketplace'),
        ),
    ]
