# Generated by Django 5.2 on 2026-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_alter_ebayconfig_marketplace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayconfig',
            name='default_ebay_shipping',
        ),
        migrations.AddField(
            model_name='ebayorderitem',
            name='shipping_to_confirm',
            field=models.BooleanField(default=False, help_text='eBay no informó el costo de envío de esta publicación: hay que cargarlo a mano.', verbose_name='Envío eBay a confirmar'),
        ),
    ]
