# Generated by Django 5.1.2 on 2026-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Home'), ('pokemon', 'Pokémon'), ('lorcana', 'Lorcana'), ('one_piece', 'One Piece'), ('yugioh', 'Yu-Gi-Oh!'), ('checkout', 'Checkout'), ('store', 'Tienda')], max_length=50, unique=True)),
                ('image_url', models.URLField(max_length=600)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción de email',
                'verbose_name_plural': 'Suscripciones de email',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para mostrar página de mantenimiento.')),
                ('maintenance_message', models.CharField(blank=True, default='Sitio en mantenimiento. Volvemos pronto.', max_length=500)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
