# Generated by Django 5.2 on 2026-04-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
