# Generated by Django 5.1.2 on 2026-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Suscripto el'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='usd_to_ars',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Valor del dólar en pesos. Ej: 1450.00', max_digits=10, verbose_name='USD a ARS'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivar para mostrar página de mantenimiento.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='maintenance_message',
            field=models.CharField(blank=True, default='Sitio en mantenimiento. Volvemos pronto.', max_length=500, verbose_name='Mensaje de mantenimiento'),
        ),
    ]
