# Generated by Django 5.2 on 2026-04-14 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_cash_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Configuración de pago en efectivo',
                'verbose_name_plural': 'Configuración de pago en efectivo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfig',),
        ),
        migrations.AlterModelOptions(
            name='emailsubscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Suscripción de email', 'verbose_name_plural': 'Suscripciones de email'},
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(help_text='Línea de asunto que verán los suscriptores', max_length=255, verbose_name='Asunto del email')),
                ('contenido', models.TextField(help_text='HTML/Texto del email a enviar. Puedes usar {{email}} como variable.', verbose_name='Contenido del email')),
                ('imagen_url', models.URLField(blank=True, help_text='Enlace a una imagen para incluir en el email (ej: banner de oferta)', max_length=500, null=True, verbose_name='URL de imagen')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='borrador', help_text='Estado actual de la campaña', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Se completa al enviar', null=True, verbose_name='Enviada el')),
                ('cantidad_enviados', models.PositiveIntegerField(default=0, verbose_name='Emails enviados')),
                ('cantidad_fallidos', models.PositiveIntegerField(default=0, verbose_name='Emails fallidos')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Campaña de email',
                'verbose_name_plural': 'Campañas de email',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
