# Generated by Django 5.2 on 2026-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_card_surcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Datos de transferencia',
                'verbose_name_plural': 'Datos de transferencia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfig',),
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='core_emaild_last_re_4b29a7_idx',
            old_name='core_emaildel_last_recv_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='core_emaild_status_bc362a_idx',
            old_name='core_emaildel_status_idx',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='transfer_alias',
            field=models.CharField(blank=True, default='', help_text='Se muestra en el checkout con botón de copiar.', max_length=100, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='transfer_bank',
            field=models.CharField(blank=True, default='', help_text='Ej: Mercado Pago, Banco Galicia. Se muestra en el checkout.', max_length=100, verbose_name='Banco / billetera'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='transfer_cbu',
            field=models.CharField(blank=True, default='', help_text='Se muestra en el checkout con botón de copiar.', max_length=40, verbose_name='CBU / CVU'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='transfer_holder',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del titular, tal como figura en el banco.', max_length=150, verbose_name='Titular de la cuenta'),
        ),
    ]
