# Generated by Django 5.2 on 2026-04-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_ensure_tables_exist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishlistItem",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
