# Generated by Django 5.2 on 2026-08-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_productimage_productimagewebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abbreviation', models.CharField(blank=True, db_index=True, help_text='Código corto del set. Ej: "SV9a", "s12a".', max_length=50, verbose_name='Abreviatura')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('language', models.CharField(choices=[('en', 'Inglés'), ('ja', 'Japonés')], db_index=True, default='en', max_length=5, verbose_name='Idioma')),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('is_supplemental', models.BooleanField(default=False, help_text='Promos, decks y productos fuera de las expansiones principales.', verbose_name='Suplementario')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='Importado')),
                ('tcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='products.tcg', verbose_name='TCG')),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
                'ordering': ['-released_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID externo')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Número')),
                ('rarity', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Rareza')),
                ('search_text', models.CharField(blank=True, db_index=True, max_length=600, verbose_name='Texto de búsqueda')),
                ('source_url', models.URLField(blank=True, max_length=600, verbose_name='URL de origen')),
                ('source_image_url', models.URLField(blank=True, max_length=600, verbose_name='Imagen de origen')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Imagen')),
                ('image_url_medium', models.URLField(blank=True, max_length=600, verbose_name='Imagen media')),
                ('image_url_thumb', models.URLField(blank=True, max_length=600, verbose_name='Miniatura')),
                ('image_status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Lista'), ('failed', 'Fallida')], db_index=True, default='pending', max_length=20, verbose_name='Estado de imagen')),
                ('image_error', models.TextField(blank=True, verbose_name='Error de imagen')),
                ('extended_data', models.JSONField(blank=True, default=dict, verbose_name='Datos extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.cardset', verbose_name='Expansión')),
            ],
            options={
                'verbose_name': 'Carta del catálogo',
                'verbose_name_plural': 'Catálogo de cartas',
                'ordering': ['card_set', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='cardset',
            index=models.Index(fields=['language', 'name'], name='catalog_car_languag_85f13f_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcard',
            index=models.Index(fields=['card_set', 'number'], name='catalog_cat_card_se_0a8c93_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcard',
            index=models.Index(fields=['image_status'], name='catalog_cat_image_s_8ee00d_idx'),
        ),
    ]
