# Generated by Django 5.2 on 2026-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='source_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modificado en origen'),
        ),
    ]
