# Generated by Django 5.2 on 2026-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogcard_search_trigram_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='printings_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acabados al día'),
        ),
        migrations.AddField(
            model_name='catalogcard',
            name='printings',
            field=models.JSONField(blank=True, default=list, verbose_name='Acabados'),
        ),
    ]
