# Generated by Django 5.2 on 2026-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cardset_printings_synced_at_catalogcard_printings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='printings_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Detalles al día'),
        ),
        migrations.AlterField(
            model_name='catalogcard',
            name='printings',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalles'),
        ),
    ]
